### ISSUE TITLE
Update minimatch for security reasons

### ISSUE THREAD

**Issue by stephanmax** [nsonnad/metalsmith-slug#13]
Hi @nsonnad, I am still using this wonderful Metalsmith plugin and would love to see its dependencies being updated. I notices you haven’t updated the repo in a while—do you mind me asking if you would be willing to transfer the repo to me so I can maintain it?
Thanks in advance!

**Comment by nsonnad** [comment]
Hey @stephanmax, sorry for such a long delay, have had a bit of a github hiatus. Are you still using the plugin? Would be happy to transfer to you if so!

**Comment by stephanmax** [comment]
Hey @nsonnad, thanks a mill for getting back at me—I hope you are safe and well.

Yes, I am using the plugin and am still up for maintaining it.

**Comment by nsonnad** [comment]
I have initiated the transfer. Glad you're using the plugin! And sorry again for the delays.

**Comment by stephanmax** [comment]
Sorry to bother you one last time, @nsonnad. But I am afraid you would also have to transfer the npm package https://www.npmjs.com/package/metalsmith-slug to me.

**Comment by nsonnad** [comment]
done!

**Comment by stephanmax** [comment]
Awesome, thanks a lot, @nsonnad. I will take good care of this package!
