### ISSUE TITLE
Version 0.6.0 not published in NPM

### ISSUE THREAD

**Issue by doup** [nsonnad/metalsmith-slug#3]
Here 0.5.0: https://www.npmjs.com/package/metalsmith-slug
For reference: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by doup** [comment]
Since I propose a PR #5, it would be nice to mark b086f834a72a as `0.6.0` and the PR as `0.7.0`. What do you think @nsonnad?

**Comment by doup** [comment]
@nsonnad, what about tagging before merging the PR?

**Comment by tunix** [comment]
+1

**Comment by almirfilho** [comment]
Is there any update on this? @nsonnad could you please publish version 0.0.6 to NPM? Thanks!

**Comment by nsonnad** [comment]
Sorry about all that... versions 0.0.6, 0.0.7, 0.0.8, and 0.1.0 are now published

**Comment by almirfilho** [comment]
@nsonnad only version 0.0.6 is published. https://www.npmjs.com/package/metalsmith-slug

**Comment by nsonnad** [comment]
Ah sorry, I often do `version` and forget to `publish`. I have published 0.1.0
